# Generated by Django 4.0.5 on 2022-06-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_rename_tags_tag_sideimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
