# Generated by Django 4.0.5 on 2022-06-22 10:17

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal(1), max_digits=50),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal(1), max_digits=50),
        ),
    ]
