# Generated by Django 4.0.5 on 2022-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='formatted_address',
            field=models.TextField(default=''),
        ),
    ]
